package cn.ksmcbrigade.mixinyes;

import java.util.List;

/**
 * &#064;Author: KSmc_brigade
 * &#064;Date: 2025/11/21
 */
public class Constants {
    public static final List<String> VANILLA_MODULES = List.of(
            "fmlearlydisplay",
            "org.lwjgl.glfw.natives",
            "patchy",
            "blocklist",
            "org.lwjgl.openal",
            "io.netty.transport",
            "org.joml",
            "mergetool",
            "failureaccess",
            "org.apache.httpcomponents.httpclient",
            "jline.terminal",
            "org.lwjgl.stb.natives",
            "logging",
            "org.apache.commons.lang3",
            "io.netty.transport.unix.common",
            "accesstransformers",
            "authlib",
            "maven.artifact",
            "jline.reader",
            "terminalconsoleappender",
            "datafixerupper",
            "com.sun.jna.platform",
            "cpw.mods.modlauncher",
            "org.lwjgl",
            "org.lwjgl.opengl.natives",
            "com.electronwill.nightconfig.core",
            "commons.logging",
            "com.sun.jna",
            "net.minecraftforge.coremod",
            "org.openjdk.nashorn",
            "org.apache.httpcomponents.httpcore",
            "org.slf4j",
            "org.lwjgl.glfw",
            "com.github.oshi",
            "org.lwjgl.stb",
            "io.netty.resolver",
            "JarJarMetadata",
            "net.minecraftforge.forgespi",
            "org.apache.logging.log4j.core",
            "com.ibm.icu",
            "JarJarSelector",
            "com.google.common",
            "jopt.simple",
            "fmlloader",
            "org.antlr.antlr4.runtime",
            "com.electronwill.nightconfig.toml",
            "io.netty.transport.classes.epoll",
            "org.apache.commons.io",
            "org.lwjgl.jemalloc",
            "io.netty.handler",
            "org.apache.logging.log4j.slf4j",
            "unsafe",
            "io.netty.buffer",
            "org.spongepowered.mixin",
            "org.lwjgl.tinyfd",
            "text2speech",
            "org.apache.logging.log4j",
            "net.jodah.typetools",
            "org.lwjgl.openal.natives",
            "io.netty.codec",
            "org.apache.commons.compress",
            "net.minecraftforge.eventbus",
            "com.google.gson",
            "org.apache.commons.codec",
            "brigadier",
            "org.lwjgl.jemalloc.natives",
            "org.lwjgl.opengl",
            "io.netty.common",
            "org.lwjgl.tinyfd.natives",
            "it.unimi.dsi.fastutil",
            "org.lwjgl.natives",
            "mc1._20._1",
            "io.netty.transport.epoll.linux.x86_64",
            "io.netty.transport.epoll.linux.aarch_64",
            "server"
    );
}
