#General settings
[general]

	[general.render]
		#PlayerHealthBar
		playerHealthBar = true
		#TitanSwordOldModel
		titanSwordOldModel = false

		[general.render.titanPartBoxColor]
			#TitanPartBoxRed
			#Range: 0 ~ 255
			titanPartBoxRed = 64
			#TitanPartBoxGreen
			#Range: 0 ~ 255
			titanPartBoxGreen = 255
			#TitanPartBoxBlue
			#Range: 0 ~ 255
			titanPartBoxBlue = 0

		[general.render.titanBossBar]
			#TitanBossBarRange
			#Range: 0 ~ 1024
			titanBossBarRange = 256
			#TitanBossBarAnimated
			titanBossBarAnimated = true

		[general.item.voidArmor]
			#VoidArmorRadiationPlayer
			voidArmorRadiationPlayer = true

		[general.item.adminiumArmor]
			#AdminiumArmorRadiationPlayer
			adminiumArmorRadiationPlayer = true
			#AdminiumArmorExplode
			adminiumArmorExplode = true
			#AdminiumArmorGravity
			adminiumArmorGravity = true

		[general.entity.omegafish]
			#OmegafishSubduerate
			#Range: 0.0 ~ 100.0
			omegafishSubduerate = 0.009999999776482582

		[general.entity.creeperTitan]
			#CreeperTitanExplodeAsync
			creeperTitanExplodeAsync = false
			#CreeperTitanExplodeRange
			#Range: 0 ~ 1024
			creeperTitanExplodeRange = 128
			#ChargedCreeperTitanExplodeRange
			#Range: 0 ~ 1024
			chargedCreeperTitanExplodeRange = 256

		[general.entity.caveSpiderTitan]
			#CaveSpiderTitanSubduerate
			#Range: 0.0 ~ 100.0
			caveSpiderTitanSubduerate = 0.009999999776482582

		[general.spawn.spawnProtect]
			#PlayerSpawnPosProtect
			playerSpawnPosProtect = true
			#PlayerSpawnPosDistance
			#Range: 0.0 ~ 2048.0
			playerSpawnPosDistance = 1024.0
			#TitanSpawnNetherTop
			titanSpawnNetherTop = true

			[general.spawn.spawnRate.minion]
				#MinionSpawnrate
				#Range: 0.0 ~ 100.0
				minionSpawnrate = 100.0
				#PriestSpawnrate
				#Range: 0.0 ~ 100.0
				priestSpawnrate = 25.0
				#ZealotSpawnrate
				#Range: 0.0 ~ 100.0
				zealotSpawnrate = 12.5
				#BishopSpawnrate
				#Range: 0.0 ~ 100.0
				bishopSpawnrate = 5.0
				#TemplarSpawnrate
				#Range: 0.0 ~ 100.0
				templarSpawnrate = 1.25

			[general.spawn.spawnRate.titan]
				#SlimeTitanSpawnrate
				#Range: 0.0 ~ 100.0
				slimeTitanSpawnrate = 0.10000000149011612
				#MagmaCubeTitanSpawnrate
				#Range: 0.0 ~ 100.0
				magmaCubeTitanSpawnrate = 0.05000000074505806
				#OmegafishSpawnrate
				#Range: 0.0 ~ 100.0
				omegafishSpawnrate = 0.07999999821186066
				#ZombieTitanSpawnrate
				#Range: 0.0 ~ 100.0
				zombieTitanSpawnrate = 0.05000000074505806
				#SkeletonSpawnrate
				#Range: 0.0 ~ 100.0
				skeletonSpawnrate = 0.05000000074505806
				#WitherSkeletonSpawnrate
				#Range: 0.0 ~ 100.0
				witherSkeletonSpawnrate = 0.02500000037252903
				#CreeperTitanSpawnrate
				#Range: 0.0 ~ 100.0
				creeperTitanSpawnrate = 0.05000000074505806
				#SpiderTitanSpawnrate
				#Range: 0.0 ~ 100.0
				spiderTitanSpawnrate = 0.07999999821186066
				#CaveSpiderTitanSpawnrate
				#Range: 0.0 ~ 100.0
				caveSpiderTitanSpawnrate = 0.07999999821186066
				#SpiderJockeyTitanSpawnrate
				#Range: 0.0 ~ 100.0
				spiderJockeyTitanSpawnrate = 0.012500000186264515
				#PigZombieTitanSpawnrate
				#Range: 0.0 ~ 100.0
				pigZombieTitanSpawnrate = 0.05000000074505806
				#BlazeTitanSpawnrate
				#Range: 0.0 ~ 100.0
				blazeTitanSpawnrate = 0.02500000037252903
				#EnderColossusSpawnrate
				#Range: 0.0 ~ 100.0
				enderColossusSpawnrate = 0.0020000000949949026
				#GhastTitanSpawnrate
				#Range: 0.0 ~ 100.0
				ghastTitanSpawnrate = 0.012500000186264515

			[general.spawn.spawncap.protoBall]
				#ProtoBallMinionSpawncap
				#Range: 0 ~ 1000
				protoBallMinionSpawncap = 40
				#ProtoBallPriestSpawncap
				#Range: 0 ~ 1000
				protoBallPriestSpawncap = 20
				#ProtoBallZealotSpawncap
				#Range: 0 ~ 1000
				protoBallZealotSpawncap = 10
				#ProtoBallBishopSpawncap
				#Range: 0 ~ 1000
				protoBallBishopSpawncap = 5

			[general.spawn.spawncap.omegafish]
				#OmegafishMinionSpawnCap
				#Range: 0 ~ 1000
				omegafishMinionSpawnCap = 240
				#OmegafishPriestSpawnCap
				#Range: 0 ~ 1000
				omegafishPriestSpawnCap = 120
				#OmegafishZealotSpawnCap
				#Range: 0 ~ 1000
				omegafishZealotSpawnCap = 60
				#OmegafishBishopSpawnCap
				#Range: 0 ~ 1000
				omegafishBishopSpawnCap = 15
				#OmegafishTemplarSpawnCap
				#Range: 0 ~ 1000
				omegafishTemplarSpawnCap = 8

			[general.spawn.spawncap.zombieTitan]
				#ZombieTitanMinionSpawnCap
				#Range: 0 ~ 1000
				zombieTitanMinionSpawnCap = 200
				#ZombieTitanPriestSpawnCap
				#Range: 0 ~ 1000
				zombieTitanPriestSpawnCap = 100
				#ZombieTitanZealotSpawnCap
				#Range: 0 ~ 1000
				zombieTitanZealotSpawnCap = 50
				#ZombieTitanBishopSpawnCap
				#Range: 0 ~ 1000
				zombieTitanBishopSpawnCap = 20
				#ZombieTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				zombieTitanTemplarSpawnCap = 10
				#ZombieTitanSpecialSpawnCap
				#Range: 0 ~ 1000
				zombieTitanSpecialSpawnCap = 5

			[general.spawn.spawncap.skeletonTitan]
				#SkeletonTitanMinionSpawnCap
				#Range: 0 ~ 1000
				skeletonTitanMinionSpawnCap = 160
				#SkeletonTitanPriestSpawnCap
				#Range: 0 ~ 1000
				skeletonTitanPriestSpawnCap = 90
				#SkeletonTitanZealotSpawnCap
				#Range: 0 ~ 1000
				skeletonTitanZealotSpawnCap = 40
				#SkeletonTitanBishopSpawnCap
				#Range: 0 ~ 1000
				skeletonTitanBishopSpawnCap = 20
				#SkeletonTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				skeletonTitanTemplarSpawnCap = 10

			[general.spawn.spawncap.witherSkeletonTitan]
				#WitherSkeletonTitanMinionSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanMinionSpawnCap = 160
				#WitherSkeletonTitanPriestSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanPriestSpawnCap = 90
				#WitherSkeletonTitanZealotSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanZealotSpawnCap = 40
				#WitherSkeletonTitanBishopSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanBishopSpawnCap = 20
				#WitherSkeletonTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanTemplarSpawnCap = 10
				#WitherSkeletonTitanSpecialSpawnCap
				#Range: 0 ~ 1000
				witherSkeletonTitanSpecialSpawnCap = 6

			[general.spawn.spawncap.creeperTitan]
				#CreeperTitanMinionSpawnCap
				#Range: 0 ~ 1000
				creeperTitanMinionSpawnCap = 120
				#CreeperTitanPriestSpawnCap
				#Range: 0 ~ 1000
				creeperTitanPriestSpawnCap = 60
				#CreeperTitanZealotSpawnCap
				#Range: 0 ~ 1000
				creeperTitanZealotSpawnCap = 30
				#CreeperTitanBishopSpawnCap
				#Range: 0 ~ 1000
				creeperTitanBishopSpawnCap = 15
				#CreeperTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				creeperTitanTemplarSpawnCap = 8

			[general.spawn.spawncap.spiderTitan]
				#SpiderTitanMinionSpawnCap
				#Range: 0 ~ 1000
				spiderTitanMinionSpawnCap = 160
				#SpiderTitanPriestSpawnCap
				#Range: 0 ~ 1000
				spiderTitanPriestSpawnCap = 80
				#SpiderTitanZealotSpawnCap
				#Range: 0 ~ 1000
				spiderTitanZealotSpawnCap = 40
				#SpiderTitanBishopSpawnCap
				#Range: 0 ~ 1000
				spiderTitanBishopSpawnCap = 20
				#SpiderTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				spiderTitanTemplarSpawnCap = 7

			[general.spawn.spawncap.caveSpiderTitan]
				#CaveSpiderTitanMinionSpawnCap
				#Range: 0 ~ 1000
				caveSpiderTitanMinionSpawnCap = 180
				#CaveSpiderTitanPriestSpawnCap
				#Range: 0 ~ 1000
				caveSpiderTitanPriestSpawnCap = 80
				#CaveSpiderTitanZealotSpawnCap
				#Range: 0 ~ 1000
				caveSpiderTitanZealotSpawnCap = 20
				#CaveSpiderTitanBishopSpawnCap
				#Range: 0 ~ 1000
				caveSpiderTitanBishopSpawnCap = 15
				#CaveSpiderTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				caveSpiderTitanTemplarSpawnCap = 4

			[general.spawn.spawncap.pigZombieTitan]
				#PigZombieTitanMinionSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanMinionSpawnCap = 200
				#PigZombieTitanPriestSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanPriestSpawnCap = 100
				#PigZombieTitanZealotSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanZealotSpawnCap = 50
				#PigZombieTitanBishopSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanBishopSpawnCap = 20
				#PigZombieTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanTemplarSpawnCap = 10
				#PigZombieTitanSpecialSpawnCap
				#Range: 0 ~ 1000
				pigZombieTitanSpecialSpawnCap = 5

			[general.spawn.spawncap.blazeTitan]
				#BlazeTitanMinionSpawnCap
				#Range: 0 ~ 1000
				blazeTitanMinionSpawnCap = 120
				#BlazeTitanPriestSpawnCap
				#Range: 0 ~ 1000
				blazeTitanPriestSpawnCap = 60
				#BlazeTitanZealotSpawnCap
				#Range: 0 ~ 1000
				blazeTitanZealotSpawnCap = 20
				#BlazeTitanBishopSpawnCap
				#Range: 0 ~ 1000
				blazeTitanBishopSpawnCap = 15
				#BlazeTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				blazeTitanTemplarSpawnCap = 8

			[general.spawn.spawncap.enderColossus]
				#EnderColossusMinionSpawnCap
				#Range: 0 ~ 1000
				enderColossusMinionSpawnCap = 160
				#EnderColossusPriestSpawnCap
				#Range: 0 ~ 1000
				enderColossusPriestSpawnCap = 80
				#EnderColossusZealotSpawnCap
				#Range: 0 ~ 1000
				enderColossusZealotSpawnCap = 40
				#EnderColossusBishopSpawnCap
				#Range: 0 ~ 1000
				enderColossusBishopSpawnCap = 30
				#EnderColossusTemplarSpawnCap
				#Range: 0 ~ 1000
				enderColossusTemplarSpawnCap = 20
				#EnderColossusSpecialSpawnCap
				#Range: 0 ~ 1000
				enderColossusSpecialSpawnCap = 10

			[general.spawn.spawncap.ghastTitan]
				#GhastTitanMinionSpawnCap
				#Range: 0 ~ 1000
				ghastTitanMinionSpawnCap = 120
				#GhastTitanPriestSpawnCap
				#Range: 0 ~ 1000
				ghastTitanPriestSpawnCap = 60
				#GhastTitanZealotSpawnCap
				#Range: 0 ~ 1000
				ghastTitanZealotSpawnCap = 30
				#GhastTitanBishopSpawnCap
				#Range: 0 ~ 1000
				ghastTitanBishopSpawnCap = 15
				#GhastTitanTemplarSpawnCap
				#Range: 0 ~ 1000
				ghastTitanTemplarSpawnCap = 8

			[general.spawn.spawncap.witherzilla]
				#WitherzillaMinionSpawnCap
				#Range: 0 ~ 10000
				witherzillaMinionSpawnCap = 1000

		[general.spawn.summon]
			#TemplarSummonLoyalistSpawnrate
			#Range: 0.0 ~ 100.0
			templarSummonLoyalistSpawnrate = 0.16699999570846558
			#TemplarSummonPriestSpawnrate
			#Range: 0.0 ~ 100.0
			templarSummonPriestSpawnrate = 0.08299999684095383
			#TemplarSummonZealotSpawnrate
			#Range: 0.0 ~ 100.0
			templarSummonZealotSpawnrate = 0.041999999433755875
			#SnowGolemMinionSpawnrate
			#Range: 0.0 ~ 100.0
			snowGolemMinionSpawnrate = 5.0
			#IronGolemMinionSpawnrate
			#Range: 0.0 ~ 100.0
			ironGolemMinionSpawnrate = 5.0
			#TitanSummonLoyalistSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonLoyalistSpawnrate = 5.0
			#TitanSummonPriestSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonPriestSpawnrate = 2.5
			#TitanSummonZealotSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonZealotSpawnrate = 1.25
			#TitanSummonBishopSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonBishopSpawnrate = 0.625
			#TitanSummonTemplarSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonTemplarSpawnrate = 0.3125
			#TitanSummonSpecialMinionSpawnrate
			#Range: 0.0 ~ 100.0
			titanSummonSpecialMinionSpawnrate = 0.3125
			#ZombieTitanSummonSpecialMinionSpawnrate
			#Range: 0.0 ~ 100.0
			zombieTitanSummonSpecialMinionSpawnrate = 0.3125
			#PigZombieTitanSummonSpecialMinionSpawnrate
			#Range: 0.0 ~ 100.0
			pigZombieTitanSummonSpecialMinionSpawnrate = 0.3125
			#EnderColossusSummonSpecialMinionSpawnrate
			#Range: 0.0 ~ 100.0
			enderColossusSummonSpecialMinionSpawnrate = 0.3125
