name: DevMixinYes Gradle Build

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew --no-daemon clean jarJar build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mixinYes-artifacts-${{ github.sha }}
          if-no-files-found: warn
          retention-days: 14
          path: |
            build/libs/*.jar
            !**/*-sources.jar
            !**/*-javadoc.jar
            !**/*-dev.jar